version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: python ./app/app.py
    stdin_open: true
    tty: true
    ports:
      - 5000:80